PUT http://localhost:3001/api/users/favorites/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBhbG11cGUiLCJpZCI6IjVlNjY3NDk0Mzg4Y2NlNGFiN2FmZDY1NCIsImlhdCI6MTU4Mzg1MjU0OX0.3SGrLNnd1rvrAiZSw2QtxF4jfMuPnNjXobQ7s5c9WyQ

{
  "favorite": "Germany"
}
